#!/bin/bash
set -euo pipefail

# RCT-Engine Cultural Risk Report Generator

OUTPUT_DIR="${1:-./reports}"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
REPORT_FILE="$OUTPUT_DIR/cultural_risk_report_$TIMESTAMP.md"

mkdir -p "$OUTPUT_DIR"

echo "📊 Generating Cultural Risk Report"
echo "=========================================="

# Fetch data from database
get_top_risks() {
    docker exec rct-postgres psql -U rct_admin -d rct_saas -t -A -F'|' -c "
        SELECT 
            country_code,
            COUNT(*) as total_blocks,
            COUNT(*) FILTER (WHERE risk_level = 'CRITICAL') as critical_blocks,
            COUNT(*) FILTER (WHERE risk_level = 'MEDIUM') as medium_blocks,
            ROUND(AVG(processing_time_ms)) as avg_latency
        FROM translation_audit_logs
        WHERE created_at > NOW() - INTERVAL '30 days'
        GROUP BY country_code
        ORDER BY total_blocks DESC
        LIMIT 10;
    "
}

get_top_slangs() {
    docker exec rct-postgres psql -U rct_admin -d rct_saas -t -A -F'|' -c "
        SELECT 
            unnest(detected_slangs) as slang,
            COUNT(*) as frequency,
            country_code
        FROM translation_audit_logs
        WHERE created_at > NOW() - INTERVAL '30 days'
          AND detected_slangs IS NOT NULL
        GROUP BY slang, country_code
        ORDER BY frequency DESC
        LIMIT 20;
    "
}

# Generate report
cat > "$REPORT_FILE" << EOF
# RCT-Engine Cultural Risk Report
**Generated:** $(date)
**Period:** Last 30 Days

---

## Executive Summary

| Metric | Value |
|--------|-------|
| Total Translations | $(docker exec rct-postgres psql -U rct_admin -d rct_saas -t -A -c "SELECT COUNT(*) FROM translation_audit_logs WHERE created_at > NOW() - INTERVAL '30 days';") |
| Total Critical Blocks | $(docker exec rct-postgres psql -U rct_admin -d rct_saas -t -A -c "SELECT COUNT(*) FROM translation_audit_logs WHERE created_at > NOW() - INTERVAL '30 days' AND risk_level = 'CRITICAL';") |
| Total Medium Blocks | $(docker exec rct-postgres psql -U rct_admin -d rct_saas -t -A -c "SELECT COUNT(*) FROM translation_audit_logs WHERE created_at > NOW() - INTERVAL '30 days' AND risk_level = 'MEDIUM';") |
| Risk Rate | $(docker exec rct-postgres psql -U rct_admin -d rct_saas -t -A -c "SELECT ROUND((COUNT(*) FILTER (WHERE risk_level IN ('CRITICAL','MEDIUM'))::numeric / COUNT(*)::numeric) * 100, 2) FROM translation_audit_logs WHERE created_at > NOW() - INTERVAL '30 days';")% |

---

## Top Risk Countries

| Country | Total Blocks | Critical | Medium | Avg Latency (ms) |
|---------|--------------|----------|--------|------------------|
EOF

while IFS='|' read country total critical medium latency; do
    echo "| $country | $total | $critical | $medium | $latency |" >> "$REPORT_FILE"
done < <(get_top_risks)

cat >> "$REPORT_FILE" << EOF

---

## Most Detected Slangs

| Slang | Frequency | Country |
|-------|-----------|---------|
EOF

while IFS='|' read slang frequency country; do
    echo "| $slang | $frequency | $country |" >> "$REPORT_FILE"
done < <(get_top_slangs)

cat >> "$REPORT_FILE" << EOF

---

## Recommendations

### High-Risk Countries Requiring Attention

$(docker exec rct-postgres psql -U rct_admin -d rct_saas -t -A -c "
    SELECT 
        '- **' || country_code || '**: ' || COUNT(*) || ' critical blocks in last 30 days. Review cultural matrix entries.'
    FROM translation_audit_logs
    WHERE created_at > NOW() - INTERVAL '30 days' AND risk_level = 'CRITICAL'
    GROUP BY country_code
    HAVING COUNT(*) > 10
    ORDER BY COUNT(*) DESC;
")

### New Slangs to Add to Cultural Matrix

$(docker exec rct-postgres psql -U rct_admin -d rct_saas -t -A -c "
    SELECT DISTINCT
        '- **' || unnest(detected_slangs) || '** detected in ' || country_code || ' - ' || COUNT(*) || ' times'
    FROM translation_audit_logs
    WHERE created_at > NOW() - INTERVAL '7 days'
      AND detected_slangs IS NOT NULL
    GROUP BY slang, country_code
    ORDER BY COUNT(*) DESC
    LIMIT 10;
")

---

## Appendix: Data Source

- **Database:** PostgreSQL (rct_saas)
- **Tables:** translation_audit_logs, cultural_context_matrix
- **Retention:** $RETENTION_DAYS days

---
*This report was automatically generated by RCT-Engine*
EOF

echo ""
echo "=========================================="
echo -e "\033[0;32m✅ Report generated: $REPORT_FILE\033[0m"
echo "=========================================="
